name: boilerplate
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.0.2+1
  dio: ^4.0.6
  intl: ^0.17.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.0
  flutter_slidable: ^1.3.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  mocktail: ^0.3.0
  bloc_test: ^9.0.3
  logger: ^1.1.0
  rxdart: ^0.27.4
  connectivity: ^3.0.6
  formz: ^0.4.1
  loading_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/locales/
    - assets/locals/

  fonts:
    - family: OpenSans, Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSans, SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-LightItalic.ttf
